#!/usr/bin/env bash

COMMAND="${1}"
CNF_URL="https://command-not-found.com"
DEPENDENCIES=( bash which curl xmllint grep awk sort basename echo column )

print_help() {
  echo "Usage: $(basename $0) \${COMMAND} [-h -f -p -v]"
  help_output+="  -h / --help | - prints help/usage\n"
  help_output+="  -f / --force | - force command-not-found.com query to show installation methods even if package is already installed\n"
  help_output+="  -p / --package_only | - show package names only in output - useful for automation\n"
  help_output+="  -v / --version | - prints cnf-install version\n"
  echo -e "${help_output}" | column -t -s '|'
}

print_version() {
  echo "Version: 0.4-alpha (https://github.com/N0zz/cnf-install/releases/tag/v0.4-alfa)"
}

for dep in "${DEPENDENCIES[@]}"; do

  if [[ ! -f $(which ${dep} 2>/dev/null) ]]; then
    echo "${dep} not installed. Check out ${CNF_URL}/${dep} for instructions."
    dep_failed=1
  fi

done

for i in "$@"; do
  case $i in
    -h|--help)
      print_help
      exit 0
      ;;
    -v|--version)
      print_version
      exit 0
      ;;
    -f|--force)
      force=true
      shift
      ;;
    -p|--package-only)
      package_only=true
      shift
      ;;
    *)
      ;;
  esac
done

if [[ -z ${COMMAND} ]]; then
  print_help
  exit 1
fi

if [[ -f $(which ${COMMAND} 2>/dev/null) && -z ${force} ]]; then
  echo "Command ${COMMAND} already installed."
  echo "Use -f/--force to show installation instructions anyway."
  echo "File found: $(which ${COMMAND})"
  exit 0
fi

[[ ! -z ${dep_failed} ]] && exit 1

# command-not-found.com api only has one endpoint, but its broken, thats why we need to use xmlint to parse website
# source: https://github.com/lukaszlach/commando/issues/13
mapfile -t INSTALLERS < <( curl -sSL0 "${CNF_URL}/${COMMAND}" |\
  xmllint --html --xpath "//div[starts-with(@class, 'command-install')]/dd/code" - 2>/dev/null |\
  awk -F'[><]' '{print $3}' |\
  grep -v 'cmd.cat\|docker\|sudo' |\
  sort -u \
)

if [[ "${#INSTALLERS[@]}" == 0 ]]; then
  echo "No installers available found on ${CNF_URL}/${COMMAND}"
  exit 1
fi

if [[ -z ${package_only} ]]; then
  echo "Found ${#INSTALLERS[@]} installers, searching for one available on your system..."
fi

for install_cmd in "${INSTALLERS[@]}"; do

  installer=$(echo "${install_cmd}" | cut -d' ' -f 1)
  package_name=$(echo "${install_cmd}" | awk '{print $NF}')

  if [[ $(which ${installer} 2>/dev/null) ]]; then
    installer_found=1

    if [[ -z ${package_only} ]]; then
      echo "Installer: ${installer}, Command: ${install_cmd}"
    else
      echo "${package_name}"
    fi

  else
      if [[ -z ${package_only} ]]; then
        echo "Skipping: ${installer}"
      fi
  fi

  if [[ ${installer_found} == 1 ]]; then
    break
  fi

done

if [[ -z ${installer_found} ]];then
  echo "No valid installation method found for your system."
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Perhaps you might want to install brew first (https://brew.sh/)."
  fi
fi