name: Tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y libxml2-utils

      - name: Run --help
        run: bash ./cnf-install --help

      - name: Check docker
        run: docker run -v ${{ github.workspace }}:/workspace alpine:latest 'ls workspace'
