name: Tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the test process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: alpine:latest
            options: -v ${{ github.workspace }}:/workspace
            run: |
              apk add bash curl libxml2-utils util-linux
              set -v
              bash /workspace/cnf-install --version
              bash /workspace/cnf-install --help
              bash /workspace/cnf-install http
              bash /workspace/cnf-install http --install
              bash /workspace/cnf-install http
              bash /workspace/cnf-install http --force
              bash /workspace/cnf-install http --package_only --force
