name: Tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y libxml2-utils

      - name: Run --help
        run: bash ./cnf-install --help

      - name: Run the test process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: alpine:latest
            options: -v ${{ github.workspace }}:/workspace
            run: |
              ls
              ls /workspace