name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ubuntu_tests:
    runs-on: ubuntu-latest
    name: "Ubuntu Tests"

    steps:
      - uses: actions/checkout@v3

      - name: Install shUnit2
        run: |
          wget https://raw.githubusercontent.com/kward/shunit2/master/shunit2 -O ./shunit2
          chmod +x ./shunit2

      - name: Ubuntu Tests
        uses: n0zz/docker-run-action@v4
        with:
            image: ubuntu:latest
            options: -v ${{ github.workspace }}:/workspace
            run: |
              apt-get update
              apt-get install -y bash curl libxml2-utils bsdmainutils
              chmod +x /workspace/cnf-install
              /workspace/unit_tests.sh

  alpine_tests:
    runs-on: ubuntu-latest
    name: "Alpine Tests"

    steps:
      - uses: actions/checkout@v3

      - name: Install shUnit2
        run: |
          wget https://raw.githubusercontent.com/kward/shunit2/master/shunit2 -O ./shunit2
          chmod +x ./shunit2

      - name: Alpine Tests
        uses: n0zz/docker-run-action@v4
        with:
            image: alpine:latest
            options: -v ${{ github.workspace }}:/workspace
            run: |
              apk update
              apk add bash curl libxml2-utils util-linux
              bash
              chmod +x /workspace/cnf-install
              /workspace/unit_tests.sh
